# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target '30Shine' do
pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'RealmSwift'
pod 'ReachabilitySwift'
pod 'NPSegmentedControl'
pod 'youtube-parser'
pod 'JASON'

end

